{% set name = "napkin" %}
{% set version = "0.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbc938eca99dee0f4c37bc1d6491b5826a779db468c5fdbc1b3ef58cc0e58f5a

build:
  noarch: python
  number: 1
  entry_points:
    - napkin = napkin.cli:main
    - napkin_plantuml = napkin.plantuml_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - requests
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - napkin
    - tests
  commands:
    - napkin --help
    - napkin_plantuml --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pinetr2e/napkin
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python DSL for writing PlantUML sequence diagram
  dev_url: https://github.com/pinetr2e/napkin

extra:
  recipe-maintainers:
    - psortos
    - mxr-conda
